/* Generated By:JavaCC: Do not edit this line. StrFormUniConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StrFormUniConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int NEG = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int ONLYIF = 8;
  /** RegularExpression Id. */
  int IFF = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\u00ac",
    "\u2227",
    "\u2228",
    "\u2192",
    "\u2194",
    "<VAR>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
  };

}
